### PR TITLE
MatchingByRendering test

### PR DESCRIPTION
**Pull request by BenjaminBako**
I made a test for SuperSubclassPinch.java. Its only for incrase code coverage.
And I made a test for MatchingByRendering.java and  i made test resources for this test.

### CODE REVIEW

**Comment by BenjaminBako** [comment]
With this test i increased the codecoverage in MatchingByRendering.java from 0.0% to 88.7%.

**Comment by reischlb** [comment]
For me it looks ok, but maybe it would be great if somebody else also check it.
@rglszl @DarkSetis ?

**Comment by DarkSetis** [comment]
Seems good to me

**Comment by BenjaminBako** [comment]
I made a wiki page for this test where i explained what i am doing: [here](https://github.com/IntegrOwlDiff/owl-diff-engine/wiki/AlignmentAlgorithm---MatchingByRendering-test)

**Pull request merged**
