### PR TITLE
EnityBasedDiff.java bugfixes

### PR DESCRIPTION
**Pull request by BenjaminBako**

### CODE REVIEW

**Comment by BenjaminBako** [comment]
I did my best. There is some code smell in the compareTo method. Its e.g. in line 188 "This branch's code block is the same as the block for the branch on line 182." but i think this order of if than else is not random so i didnt fixed this smells.

**Review by reischlb — COMMENTED** [review]
Are you sure that this empty diamond is ok?

I'm afraid this causes the building error, but i'm not sure about this.

**Comment by BenjaminBako** [comment]
image

**Comment by reischlb** [comment]
OK, then I think we can merge it.

**Pull request merged**
